### ISSUE TITLE
Issue With Quantum solar helmet crafting

### ISSUE THREAD

**Issue by Destiny3378** [OneDayStudios/StargateMC-Issues#10]
The recipe calls for an undamaged helmet but that is impossible due to the way the mod is made

attempt to craft it, and that is how to reproduce it.

It should craft a solar helmet

**Comment by Nerion1** [comment]
Hey Joey4213,

I have created a fix for this and will be pushed in the next update that Bysokar releases.

Thanks for letting us know!
