### ISSUE TITLE
Waypoints disappearing

### ISSUE THREAD

**Issue by RicoPeav** [OneDayStudios/StargateMC-Issues#13]
So, I made a waypoint at the stargate to be able to find my way back, then went to my base which was 500 blocks away and made a waypoint there also. Then today, I dialed up the stargate to the SGC & when I came back all the waypoints were gone.

**Comment by StargateMC** [comment]
Did you update your client in this time?

**Comment by RicoPeav** [comment]
Nope

**Comment by Destiny3378** [comment]
its a known error among players to have this happen
just relog and it fixes its just the mini map mod we use

**Comment by StargateMC** [comment]
Hi All, I've identified the cause - when a multiworld world is loaded its world name is incorrect (Its name is set to overworld) causing all worlds to overwrite eachother for waypoints.
I'm currently in the process of testing a fix.
