### ISSUE TITLE
Iris + GDO

### ISSUE THREAD

**Issue by devensiv** [OneDayStudios/StargateMC-Issues#17]
I have a iris installed on my stargate and a computer with the https://github.com/OneDayStudios/DiallingComputer
i have setup the idc code for me (it worked)
now i dialed in pressed the gdo--> transmitted idc and see what happened:
![image](https://user-images.githubusercontent.com/35898914/63040667-33995680-bec6-11e9-9f67-489a9052b585.png)

I think it is because the iris was still opening and so it still killed me ... if thats the case i would like to have the "iris open: ..." message send a bit later so people dont get confused.
If thats not the case i would like to have this bug fixed soon

**Comment by StargateMC** [comment]
Hi @DEVensiv This has been fixed, the GDO now has the capability to report if the destination Iris is OPENING or OPEN seperately, so you know.
