### ISSUE TITLE
Player Behavior!

### ISSUE THREAD

**Issue by devensiv** [OneDayStudios/StargateMC-Issues#18]
Today we had a situation where the server TpS got killed and I want to criticize the reckless behavior of two players in this situation.

It was done by a already known method so testing the serverlimits is not a valid excuse for what happened. 
![image](https://user-images.githubusercontent.com/35898914/63059183-02814c00-beef-11e9-9570-7206880b8eb3.png)

So the next thing i want to mention is a Mod who is not doing his work in the from me expected way. 
![image](https://cdn.discordapp.com/attachments/603785100391612416/611313711407300696/unknown.png)
nosknut actively engaged Joey to break the servers tps by a method that has no real use in order to test out anything on the serve (since the way was known and the problem occured earlier)
![image](https://cdn.discordapp.com/attachments/603785100391612416/611314102689857541/unknown.png)

**Comment by StargateMC** [comment]
I've temporarily banned them for 24 hours.
Nosk will lose his mod rank.
