### ISSUE TITLE
Stargates and warpdrive

### ISSUE THREAD

**Issue by devensiv** [OneDayStudios/StargateMC-Issues#5]
If you have a stargate on a warpdrive ship it bugges out on jump. means you cant use it anymore even if you are in orbit of a celestial body

**Comment by devensiv** [comment]
Breaking/replacing the gate fixes the bug....

**Comment by StargateMC** [comment]
Does the unique address change with jumps? What about after break and replace.

**Comment by devensiv** [comment]
it doesnt change after jump
it changes if you break and replace it

**Comment by Destiny3378** [comment]
NOT FIXED... lol
