### ISSUE TITLE
Crafting Recipe Tesseract

### ISSUE THREAD

**Issue by devensiv** [OneDayStudios/StargateMC-Issues#6]
the crafting recipe for the tesseract (1648) is not craftable because you would need a tesseract to craft one itself (https://oldcofh.github.io/docs/thermal-expansion/devices/tesseract/
https://oldcofh.github.io/docs/thermal-expansion/materials/tesseract-frame/) <-- default crafting

**Comment by StargateMC** [comment]
Tesseracts are deliberately disabled. They allow limitless transfer of items/ power / fluids without range restrictions in a mod I cannot modify to support the universe system for distances.
