### ISSUE TITLE
Ring teleporters

### ISSUE THREAD

**Issue by devensiv** [OneDayStudios/StargateMC-Issues#7]
Ring teleporters are anchors for warpdrive ships

**Comment by Destiny3378** [comment]
no they arnt? we use them on my ship

**Comment by StargateMC** [comment]
Confirmed I just jumped successfully with a ring transporter onboard. Youll need to specify whats happening and what messages you get on jump failure.

**Comment by devensiv** [comment]
ok i found the issue 
one platform was on the ship the other one not that might have caused it
