### ISSUE TITLE
Warpdrive Jumps

### ISSUE THREAD

**Issue by devensiv** [OneDayStudios/StargateMC-Issues#8]
there is a bug where the jump block limit is not clear (e.g. ship tells me its about ~6k blocks and i can enter hyperspace (should have to have 15k blocks))

**Comment by StargateMC** [comment]
Tested on Live & Confirmed the limit is there

![image](https://user-images.githubusercontent.com/9921203/62000264-deafbf00-b115-11e9-9a2f-d94d9af4480d.png)
